### ISSUE TITLE
Contribution Request.

### ISSUE THREAD

**Issue by antonio-pedro99** [Misians/Gelato-Aprendendo-Flutter-#2]
Hi! @LUK3D, @Misians 

Can I join you?
if you have anything on your mind/Prototype please do share so that I can contribute to this project too.
Thanks!

**Comment by Misians** [comment]
Hello, you can take the project and make changes and it can be used too, it was supposed to be a way to help me learn flutter <3 but feel free to contribute, the goal was to build this project here:
https://www.figma.com/file/agPAKG0EEfaNOkRYoFqfEg/Untitled?node-id=0%3A1
the idea is to build an ice cream shop, I intend to make the website also later

**Comment by antonio-pedro99** [comment]
@Misians  thank you!
As it is for your learning, I can contribute to it as long as you go.
